swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "TaskBuddy API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "aiotholdings@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:22250"
basePath: "/"
# tags:
#   - name: "DEP User"
#     description: ""

schemes:
  - "http"
  - "https"

paths:
  /hello:
    get:
      tags:
        - "Hello TaskBuddy"
      summary: "Hello TaskBuddy"
      produces:
        - "application/json"
      parameters:
        - name: "name"
          in: "query"
          description: "name / 1"
          type: "string"
      responses:
        200:
          description: "successful operation"

