// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	blocks "lifelogger/server/domain/blocks/model"

	mock "github.com/stretchr/testify/mock"
)

// BlocksRepository is an autogenerated mock type for the BlocksRepository type
type BlocksRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: _a0
func (_m *BlocksRepository) Save(_a0 blocks.Blocks) {
	_m.Called(_a0)
}

// NewBlocksRepository creates a new instance of BlocksRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlocksRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlocksRepository {
	mock := &BlocksRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
