// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	categories "lifelogger/server/domain/categories/model"

	mock "github.com/stretchr/testify/mock"
)

// CategoriesRepository is an autogenerated mock type for the CategoriesRepository type
type CategoriesRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: _a0
func (_m *CategoriesRepository) Save(_a0 categories.Category) {
	_m.Called(_a0)
}

// NewCategoriesRepository creates a new instance of CategoriesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoriesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoriesRepository {
	mock := &CategoriesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
