// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	dto "lifelogger/server/domain/categories/dto"

	mock "github.com/stretchr/testify/mock"
)

// CreateCategoryService is an autogenerated mock type for the CreateCategoryService type
type CreateCategoryService struct {
	mock.Mock
}

// CreateCategory provides a mock function with given fields: _a0
func (_m *CreateCategoryService) CreateCategory(_a0 dto.CreateCategoryReqDto) {
	_m.Called(_a0)
}

// NewCreateCategoryService creates a new instance of CreateCategoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateCategoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateCategoryService {
	mock := &CreateCategoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
