// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	users "lifelogger/server/domain/users/model"

	mock "github.com/stretchr/testify/mock"
)

// UsersRepository is an autogenerated mock type for the UsersRepository type
type UsersRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: _a0
func (_m *UsersRepository) Save(_a0 users.User) {
	_m.Called(_a0)
}

// NewUsersRepository creates a new instance of UsersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsersRepository {
	mock := &UsersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
