// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	dto "lifelogger/server/domain/calendar/dto"

	mock "github.com/stretchr/testify/mock"
)

// CreateCalendarService is an autogenerated mock type for the CreateCalendarService type
type CreateCalendarService struct {
	mock.Mock
}

// CreateCalendar provides a mock function with given fields: _a0
func (_m *CreateCalendarService) CreateCalendar(_a0 dto.CreateCalendarReqDto) {
	_m.Called(_a0)
}

// NewCreateCalendarService creates a new instance of CreateCalendarService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateCalendarService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateCalendarService {
	mock := &CreateCalendarService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
