// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DomainEvent is an autogenerated mock type for the DomainEvent type
type DomainEvent struct {
	mock.Mock
}

// Name provides a mock function with given fields:
func (_m *DomainEvent) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewDomainEvent creates a new instance of DomainEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDomainEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *DomainEvent {
	mock := &DomainEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
