// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	calendar "lifelogger/server/domain/calendar/model"

	mock "github.com/stretchr/testify/mock"
)

// CalendarRepository is an autogenerated mock type for the CalendarRepository type
type CalendarRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: _a0
func (_m *CalendarRepository) Save(_a0 calendar.Calendar) {
	_m.Called(_a0)
}

// NewCalendarRepository creates a new instance of CalendarRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCalendarRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CalendarRepository {
	mock := &CalendarRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
